### ISSUE TITLE
SSR fails when graphql query throw Error

### ISSUE THREAD

**Issue by mzygmunt** [lfades/next-with-apollo#56] opened 2019-05-06 14:26 UTC
Hello,
I have a problem with throwing errors by graphql (in my case with authorization).  I want to throw an Error when the user is not logged in. However, in this case, SSR doesn't work. "Loading ..." appears on the client's side, then the following message appears: "Network error: Can not read property 'req' of undefined".

**Comment by lfades** [comment] 2019-05-07 17:39
@mzygmunt GraphQL errrors in SSR are ignored to avoid the page from crashing, but this error `Network error: Can not read property 'req' of undefined` should not be happening.

**Comment by mzygmunt** [comment] 2019-05-07 21:02
So, is there any way for GraphQL errors to be passed to a component that handles them correctly? In my case, the point is for the error not to be ignored and not to crush the SSR, only to be passed to a component that will be rendered on the server side with a specific error message.

**Comment by lfades** [comment] 2019-05-11 19:40
@mzygmunt A `onError` callback can be added for it, I didn't before because usually the error contains no useful information, Idk if that has changed. `getDataFromTree` runs all the queries it finds and fails if any query fails but the error thrown is not every useful (at least not when I checked), let me know if you think I'm wrong.

Also the  `onError` link from Apollo should be a solution for this but afaik it's completely ignored by `getDataFromTree`

**Comment by aequasi** [comment] 2019-05-29 02:17
I'm also getting the `Cannot read property 'req' of undefined` error. Not a network error though


```
TypeError: Cannot read property 'req' of undefined
    at /Users/aaron/projects/secretary/website/app/node_modules/next-with-apollo/lib/withApollo.js:108:43
    at step (/Users/aaron/projects/secretary/website/app/node_modules/next-with-apollo/lib/withApollo.js:56:23)
    at Object.next (/Users/aaron/projects/secretary/website/app/node_modules/next-with-apollo/lib/withApollo.js:37:53)
    at /Users/aaron/projects/secretary/website/app/node_modules/next-with-apollo/lib/withApollo.js:31:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/aaron/projects/secretary/website/app/node_modules/next-with-apollo/lib/withApollo.js:27:12)
    at Function._a.getInitialProps (/Users/aaron/projects/secretary/website/app/node_modules/next-with-apollo/lib/withApollo.js:102:61)
    at Object.loadGetInitialProps (/Users/aaron/projects/secretary/website/app/node_modules/next-server/dist/lib/utils.js:42:35)
    at value (/Users/aaron/projects/secretary/website/app/.next/server/static/development/pages/_app.js:760:49)
    at /Users/aaron/projects/secretary/website/app/node_modules/next-with-apollo/lib/withApollo.js:115:50
    at step (/Users/aaron/projects/secretary/website/app/node_modules/next-with-apollo/lib/withApollo.js:56:23)
    at Object.next (/Users/aaron/projects/secretary/website/app/node_modules/next-with-apollo/lib/withApollo.js:37:53)
    at /Users/aaron/projects/secretary/website/app/node_modules/next-with-apollo/lib/withApollo.js:31:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/aaron/projects/secretary/website/app/node_modules/next-with-apollo/lib/withApollo.js:27:12)
    at Function._a.getInitialProps (/Users/aaron/projects/secretary/website/app/node_modules/next-with-apollo/lib/withApollo.js:102:61)
```

**Comment by lfades** [comment] 2019-07-30 23:40
Closing this for now, please re open if the issue persists and share a reproduction of it

**Closed** 2019-07-30 23:39 UTC

**Comment by ceefour** [comment] 2019-09-19 08:21
I got this a variant of this "problem" today:

```
VM6015:1 POST http://localhost:3002/graphql 400 (Bad Request)
invariant.esm.js:29 [GraphQL error]: Message: Cannot query field "quakes2s" on type "Query". Did you mean "quakes2", "quake", or "quakesCount"?, Location: [object Object], Path: undefined
invariant.esm.js:29 [Network error]: ServerError: Response not successful: Received status code 400
```

However at least in my case, it was caused by me rendering `{tsunamiEvents.error}`.

Instead I should `map()` it or use `.toString()`
