### ISSUE TITLE
Loading is "true" and data is "undefined" on route change

### ISSUE THREAD

**Issue by edk55** [lfades/next-with-apollo#84] opened 2019-10-05 14:48 UTC
Hi there! Even if the data is already in cache it shows `loading: true` and `data: undefined` on the first render of the route change. In fact the new request to the graphql api is not sending (this is not a problem, just clarifying).
I am not sure the problem is with this package, but I tried to test the issue by creating an app with same logic but with the another package (next-apollo) and there was no problem.

To reproduce the issue I created two sandboxes with the same logic but different packages (`next-apollo` and `next-with-apollo`). On the main page it loads "all users", so the data is already in cache when you are changing the route.

[Codesandbox next-apollo package (correct behaviour)](https://codesandbox.io/s/next-apollo-vw4hg):
Logs on route change
![next-apollo package](https://user-images.githubusercontent.com/7313150/66256401-26963680-e796-11e9-8bbc-b49d29051ed7.png)

[Codesandbox next-with-apollo package (incorrect behaviour)](https://codesandbox.io/s/next-with-apollo-9dg1s)
Logs on route change
![next-with-apollo package](https://user-images.githubusercontent.com/7313150/66256438-707f1c80-e796-11e9-9b63-ed3caa05097a.png)

**Comment by wesbos** [comment] 2020-01-28 19:57
Apparently this is because getDataFromTree stopped working in the browser? Is that true @lfades? 

I can confirm this is still an issue with `"@apollo/client": "^3.0.0-beta.29",` but the first log isn't happening. It logs loading false and then loading true. The data is there both times and doesn't seem to flicker on the interface at all or load my loading UI...

**Comment by lfades** [comment] 2020-01-28 20:15
Currently none of the 2 packages (or examples in Next.js) is trying to use `getDataFromTree` in the browser since it was updated to only work in the server, because of its high size, I'm closing the issue because there's nothing I can do from this side and the behavior is the expected (`getDataFromTree` won't work in a route navigation because `getInitialProps` gets executed in the browser).

**Closed by lfades** 2020-01-28 20:15 UTC
