### ISSUE TITLE
It seems "getDataFromTree" parameter is always set to NEVER

### ISSUE THREAD

**Issue by williamli** [lfades/next-with-apollo#37] opened 2018-12-04 10:59 UTC
I tried to do it WITHOUT getDataFromTree, with it set to `always`, `ssr`, `never` it seems that Apollo never tried to pull data (seems to defaulted to `never`). 

Facebook / Google failed to get anything from SSR. 

In my pages, I have something like

```
<Query query={GET_PAGE} variables={{ slug: 'terms', locale: this.props.query.locale }}>
        {({ loading, error, data, refetch, networkStatus }) => {
          console.log('querying graphql...');
          console.log('loading:', loading);
          console.log('networkStatus:', networkStatus);

```

and loading always returns true initially, even when it was the initial load from the server (SSR did not pull in data).

```
export default withApollo(
  () => new ApolloClient({ uri: GRAPHQL_URL }),
  {
    getDataFromTree: 'always'
  }
)
```

In the previous version of `next-with-apollo` `v3.2.1`, I don't think `getDataFromTree` was available, and `console.log('loading:', loading);` always was 'loaded'.

I have switched my code over to use https://github.com/zeit/next.js/blob/master/examples/with-apollo/pages/_app.js 

and it seems to be working correctly now.

In my pages, 

1. `loading` is false as soon as the site is loaded from the server (SSR)
2. subsequent load, `loading` started off as true as the app query the graphql server.

**Comment by lfades** [comment] 2018-12-04 14:15
Hi there, I'm sorry to hear that you're having problems with the package, unfortunately I'm unable to reproduce this issue, this package does the same thing of the example from next.js, with the adition of Typescript and the `getDataFromTree ` option.

If you can share a repo with the issue with me it would be awesome 🙏 , for the moment I'll close the issue as I'm unable to reproduce this.

**Closed by lfades** 2018-12-04 14:15 UTC

**Comment by williamli** [comment] 2018-12-05 18:03
How should I send you a private repo?
I can archive it and send it over to you.
Do you want to do it via email?

my email is williamli [a] bbi.io

**Comment by lfades** [comment] 2018-12-05 18:09
You should not send me a repo if it's private, if you can replicate the issue in a public repo and share a link with me, that's better.

**Comment by williamli** [comment] 2018-12-07 02:09
I will make it public for a few days. Will let you know shortly.
